
# --- --- Palladium Pickaxe Stats --- ---
attackDamagePalladiumPickaxe=7 #Attack damage of Palladium Pickaxe | default: 7
attackSpeedPalladiumPickaxe=0.5 #Attack speed of Palladium Pickaxe | default: 0.5

# --- --- Palladium Tool Tier Base Properties --- ---
speedPalladiumTier=30 #Speed value of Palladium tier | default: 30
enchantmentValuePalladiumTier=55 #Enchantment value of Palladium tier | default: 55
attackDamageBonusPalladiumTier=1 #Attack damage bonus of Palladium tier | default: 1
durabilityPalladium=5162 #Durability of Palladium tools | default: 5162
unbreakablePalladium=false #Whether Palladium tools are unbreakable | default: false

